In [1]:
import pandas as pd
import numpy as np

In [63]:
data = pd.DataFrame(
       [['female', 'New York', 'low', 4], ['female', 'London', 'medium', 3], ['male', 'New Delhi', 'high', 2],
        ['female', 'Orlando', 'low', 4], ['male', 'Paris', 'high', 3], ['female', 'New Delhi', 'high', 2]],
       columns=['Gender', 'City', 'Temperature', 'Rating'])
data

Gender       City Temperature  Rating
0  female   New York         low       4
1  female     London      medium       3
2    male  New Delhi        high       2
3  female    Orlando         low       4
4    male      Paris        high       3
5  female  New Delhi        high       2

In [64]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

In [65]:
ohe=OneHotEncoder(sparse=False)
le=LabelEncoder()

In [66]:
#To transform into the label data into integer data use the following
leValues=le.fit_transform(data['Gender'])
leValues

array([0, 0, 1, 0, 1, 0])

In [67]:
# To transform labeled encoded to integers to original data
le.inverse_transform(leValues)

array(['female', 'female', 'male', 'female', 'male', 'female'],
      dtype=object)

In [107]:
#For doing one hot encoding we need 2D array/martic so by doing reshape of above leValues we achieve following 2D array
leValuesRshape=leValues.reshape(len(leValues),1)
leValuesRshape

array([[0],
       [0],
       [1],
       [0],
       [1],
       [0]])

In [69]:
oheValues=ohe.fit_transform(leValuesRshape)

In [70]:
oheValues

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.]])

In [71]:
oheValues=pd.DataFrame(oheValues,columns=['female','male'])

In [72]:
oheValues

female  male
0     1.0   0.0
1     1.0   0.0
2     0.0   1.0
3     1.0   0.0
4     0.0   1.0
5     1.0   0.0

In [73]:
cpd=pd.concat([data,oheValues],axis=1)

In [75]:
cpd

Gender       City Temperature  Rating  female  male
0  female   New York         low       4     1.0   0.0
1  female     London      medium       3     1.0   0.0
2    male  New Delhi        high       2     0.0   1.0
3  female    Orlando         low       4     1.0   0.0
4    male      Paris        high       3     0.0   1.0
5  female  New Delhi        high       2     1.0   0.0

In [82]:
leValues1=le.fit_transform(cpd.Temperature)
leValues1

array([1, 2, 0, 1, 0, 0])

In [78]:
le.inverse_transform(leValues1)

array(['low', 'medium', 'high', 'low', 'high', 'high'], dtype=object)

In [79]:
leValues1Rshape=leValues1.reshape(len(leValues1),1)
leValues1Rshape

array([[1],
       [2],
       [0],
       [1],
       [0],
       [0]])

In [80]:
oheValues1=ohe.fit_transform(leValues1Rshape)
oheValues1

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [92]:
le.inverse_transform(range(3))

array(['high', 'low', 'medium'], dtype=object)

In [93]:
cpd1=pd.DataFrame(oheValues1,columns=le.inverse_transform(range(3)))

In [94]:
cpd1

high  low  medium
0   0.0  1.0     0.0
1   0.0  0.0     1.0
2   1.0  0.0     0.0
3   0.0  1.0     0.0
4   1.0  0.0     0.0
5   1.0  0.0     0.0

In [99]:
pd.concat([cpd,cpd1],axis=1)

Gender       City Temperature  Rating  female  male  high  low  medium
0  female   New York         low       4     1.0   0.0   0.0  1.0     0.0
1  female     London      medium       3     1.0   0.0   0.0  0.0     1.0
2    male  New Delhi        high       2     0.0   1.0   1.0  0.0     0.0
3  female    Orlando         low       4     1.0   0.0   0.0  1.0     0.0
4    male      Paris        high       3     0.0   1.0   1.0  0.0     0.0
5  female  New Delhi        high       2     1.0   0.0   1.0  0.0     0.0

In [100]:
data

Gender       City Temperature  Rating
0  female   New York         low       4
1  female     London      medium       3
2    male  New Delhi        high       2
3  female    Orlando         low       4
4    male      Paris        high       3
5  female  New Delhi        high       2

In [105]:
pd.get_dummies(data=data,columns=['Temperature','Gender'])

City  Rating  Temperature_high  Temperature_low  Temperature_medium  \
0   New York       4                 0                1                   0   
1     London       3                 0                0                   1   
2  New Delhi       2                 1                0                   0   
3    Orlando       4                 0                1                   0   
4      Paris       3                 1                0                   0   
5  New Delhi       2                 1                0                   0   

   Gender_female  Gender_male  
0              1            0  
1              1            0  
2              0            1  
3              1            0  
4              0            1  
5              1            0